### ISSUE TITLE
Debug build of example crashes on Manjaro linux + cargo 1.69.0

### ISSUE THREAD

**Issue by bitec0de** [notgull/theo#1]
Sorry, I realise this is still a WIP!

```
export RUST_BACKTRACE=1;cargo run --example winit             ✔ 
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/winit`
thread 'main' panicked at 'attempt to multiply with overflow', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-glow-0.1.0/src/lib.rs:235:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: <piet_glow::GpuContext<H> as piet_hardware::gpu_backend::GpuContext>::write_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-glow-0.1.0/src/lib.rs:235:25
   4: piet_hardware::resources::Texture<C>::write_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-hardware-0.1.0/src/resources.rs:166:9
   5: piet_hardware::atlas::Atlas<C>::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-hardware-0.1.0/src/atlas.rs:83:9
   6: piet_hardware::Source<C>::from_rc
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-hardware-0.1.0/src/lib.rs:140:25
   7: piet_hardware::Source<C>::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-hardware-0.1.0/src/lib.rs:151:9
   8: piet_glow::GlContext<H>::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-glow-0.1.0/src/lib.rs:607:9
   9: theo::desktop_gl::RenderContext::new_impl
             at ./src/desktop_gl.rs:304:21
  10: theo::desktop_gl::RenderContext::new
             at ./src/desktop_gl.rs:248:9
  11: theo::RenderContext::new
             at ./src/lib.rs:450:33
  12: winit::main::{{closure}}
             at ./examples/winit.rs:331:25
  13: winit::platform_impl::platform::sticky_exit_callback
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/linux/mod.rs:884:9
  14: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/linux/x11/mod.rs:385:17
  15: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/linux/x11/mod.rs:443:31
  16: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/linux/x11/mod.rs:498:25
  17: winit::platform_impl::platform::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/linux/mod.rs:792:56
  18: winit::event_loop::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/event_loop.rs:305:9
  19: winit::main
             at ./examples/winit.rs:274:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

The `release` build works correctly, though.

**Comment by notgull** [comment]
> Sorry, I realise this is still a WIP!

No need to apologize! Testing this kind of thing is necessary if we ever want this to stop being WIP.

The culprit looks to be [this line](https://github.com/notgull/piet-hardware/blob/6efb7d5027fb57a1823710f324351414e7d0799f/crates/piet-glow/src/lib.rs#L238) in `piet-glow`. It allocated the largest texture it can as a text atlas, but I failed to consider that this size could overflow a `u32`. It should be an easy enough fix.
